name = "mycambo-admin"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[vars]
NEXT_PUBLIC_ADMIN_URL = "https://mycambo-admin.pages.dev"